name: smalto_lustre

on:
  push:
  pull_request:

jobs:
  test-lustre:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smalto_lustre
    steps:
      - uses: actions/checkout@v6
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.15.0"
          rebar3-version: "3"
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Use local smalto dependency
        run: sed -i 's|smalto = ">= 3.0.0 and < 4.0.0"|smalto = { path = ".." }|' gleam.toml

      - run: gleam deps download
      - run: gleam test
      - run: gleam test --target javascript
      - run: gleam format --check src test
