name: smalto

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test-smalto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.14.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: gleam deps download
      - run: gleam test
      - run: gleam test --target javascript
      - run: gleam format --check src test
